// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqLxFhBupR5n7DmbwwhD_8yrJIDShy81I',
    appId: '1:851022714785:web:4a4b5b85bb87db3ae3dde0',
    messagingSenderId: '851022714785',
    projectId: 'quizlet-flutter',
    authDomain: 'quizlet-flutter.firebaseapp.com',
    storageBucket: 'quizlet-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_S5_PC2Wnwg9S2V6ME7O8O8kmn61INU',
    appId: '1:1088008147900:android:cdf5b6162d3398947b51b9',
    messagingSenderId: '851022714785',
    projectId: 'learn-english-app-c7edb',
    storageBucket: 'learn-english-app-c7edb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPq_49_ZLHMdqPmdOvTgUdOaNhVV7ePk',
    appId: '1:851022714785:ios:b6bac4dd6ceb8d03e3dde0',
    messagingSenderId: '851022714785',
    projectId: 'quizlet-flutter',
    storageBucket: 'quizlet-flutter.appspot.com',
    iosBundleId: 'com.example.quizletFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPq_49_ZLHMdqPmdOvTgUdOaNhVV7ePk',
    appId: '1:851022714785:ios:d255245e268d2157e3dde0',
    messagingSenderId: '851022714785',
    projectId: 'quizlet-flutter',
    storageBucket: 'quizlet-flutter.appspot.com',
    iosBundleId: 'com.example.quizletFinalFlutter.RunnerTests',
  );
}
